name: Update Toffee M3U8
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "kgkaku"
          git config --global user.email "kgkaku@users.noreply.github.com"
          git add toffee_OTT_Navigator.m3u toffee_channel_data.json
          git commit -m "Update Playlist" || echo "No changes to commit"
          git push
